development:
  password: shptka_36483a8c5f465f253ab532aba0c57d13
  theme_id: "131565158621" 
  store: new-ecommerce-wired.myshopify.com
  directory: dist/
  ignore_files:
    - config/settings_data.json
    - templates/*.json