development:
  password: shptka_4866a63568b3fb61bc832ec9a6ba01c5
  theme_id: "128704577690"
  store: abinash1.myshopify.com
  directory: dist/
  ignore_files:
    - config/settings_data.json
    - templates/*.json